#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.join(File.expand_path(File.dirname(__FILE__)), 'lib'))
require 'bundler'
Bundler.require # removes need for 'bundle exec'

require 'twitter_auth'
require 'twitter'
require 'yajl'

$stdout.sync = true

begin
  object_count = Integer(ARGV[0])
rescue ArgumentError, TypeError
  object_count = 1024
end

client = Twitter::Streaming::Client.new(:raw_data => true) do |config|
  twauth                     = TwitterAuth.new
  config.consumer_key        = twauth.consumer_key
  config.consumer_secret     = twauth.consumer_secret
  config.access_token        = twauth.access_token
  config.access_token_secret = twauth.access_token_secret
end

first = true
delete_regex = /^{"delete":/
begin
  $stdout.puts("[")
  client.sample do |data|
    unless delete_regex.match(data)
      Yajl::Parser.parse(data) do |parsed|
        $stdout.puts(",") unless first
        first = false if first
        Yajl::Encoder.encode(parsed, $stdout, :pretty => true)
      end
    end
  end
rescue Interrupt
  $stdout.puts("]")
  $stderr.puts("Exiting!")
rescue => e
  $stderr.puts("Exception: #{e}\n#{e.backtrace}")
end
